### ISSUE TITLE
US_915 Gateway shipped as EU_868

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsProducts/gateway#35]
This is a **bug report**

### What do you want to do? What do you expect?
Connect my gateway to TTN. Gateway is packaged as EU_868. The Gateway module has a printed label "LG8271".

### What steps did you take? (Give as many details as possible so that we can reproduce it)
* Connect Gateway to power supply.
* Activate using the Activation procedure(frequency plan EU_868)

### What went wrong? What is missing?
* LED 3 fast blink. Not activated. 

### What do the logs show?
*  LORA: ERROR: wrong frequency configuration, fallback on default
[SerialLogs.txt](https://github.com/TheThingsProducts/gateway/files/1902963/SerialLogs.txt)

### Any Screenshots or Photos?
<img width="262" alt="screen shot 2018-04-12 at 09 54 11" src="https://user-images.githubusercontent.com/13186113/38675412-eba19422-3e57-11e8-9bd5-3c209f63d0fb.png">

### Do you think you can try to fix this yourself and submit a pull request?

The gateway should work fine if configured to US_915, but this is a hardware labeling mismatch and not a software issue.

**Comment by KrishnaIyer** [comment]
ping @wienke

**Comment by rish-c** [comment]
Fixed
