### ISSUE TITLE
TTN Gateway range went from +1km to 10m

### ISSUE THREAD

**Issue by DutchMcGyver** [TheThingsProducts/gateway#44]
Hi, my TTN gateway has been functioning perfectly but seems to have suddenly gone quite deaf… Tested side by side with an IC880A - based gateway (using the same pigtail & antenna) the difference is very noticeable. Messages from the same node are received by the IC880A with RSSI -65, but the TTN gateway reports -118 (!). Anything outside of a 10 - 20 meter radius is not received at all.
It seems that the RF module is causing this issue; a reboot did not make any difference.

### Do you think you can try to fix this yourself and submit a pull request? - I can fix this myself if a replacement RF module is available.

If more information is needed please let me know?
Thanks,
Marc.

**Comment by KrishnaIyer** [comment]
@DutchMcGyver : Could you confirm the firmware that you're gateway is running? v1.0.0 right.

Also where have you mounted your gateway?

**Comment by DutchMcGyver** [comment]
Hi,
The gateway is still running V1.0.0. I've turned off automatic updates because it is running fine and i want to decide for myself when to run an update.
The gateway used to be located on the 3rd floor of my house. Range was over a kilometer at first, but is now limited to in and around the house (even with an external antenna).
Both the antenna and the pigtail have been replaced, this does not make any difference. The pigtail and antenna still work perfectly fine when connected to another (IC880A based) gateway.
The only thing I cannot do is replace the Microchip RF module because I only have one TTN gateway. I can however bring the gateway to the office in Amsterdam to switch out parts if that would be useful.
Regards,
Marc.

**Comment by DutchMcGyver** [comment]
Hi, is there any news on this please? As mentioned, i'm ok with having to replace the RF module myself, but i am unable to source this part...

**Comment by KrishnaIyer** [comment]
@martinichka : Seems like a hardware issue. Can you check what could be the issue here?

**Comment by DutchMcGyver** [comment]
Hi, do you have an update for me please? We are currently rolling out TTN in our region and will need every gateway we can get...
Thanks, Marc.

**Comment by DutchMcGyver** [comment]
Any updates please? We're more than willing to run some experiments but we will need information on where to get a replacement RF module as it is not listed on the Microchip website.

**Comment by DutchMcGyver** [comment]
This issue has now been open for over a month, and not a single reaction. This is bad service, and I think I'm not the only one feeling this way. Again, I'm quite willing to take some action myself, but the least I can expect is some form of communication? I've spent some 300 Euros on a device that does not work.

**Comment by Sypheos** [comment]
@DutchMcGyver Be reminded that we do not support old firmware version.

You can try to extract logs from by connecting to the serial interface as instructed here.
https://www.thethingsnetwork.org/docs/gateways/gateway/faq.html

**Comment by DutchMcGyver** [comment]
@Sypheos The firmware version has nothing to do with this as far as i can tell. The gateway was functioning perfectly, and it still is. The range has dropped dramatically from one day to the other (while on the same firmware version). I do not have a UART interface so I cannot get debug info right now.
However, I have now enabled automatic updates so it can pick up the latest firmware. If you really need debug info please let me know and I will order a UART.

**Comment by mellbratt** [comment]
(Following this as I have the same issue..)

**Comment by Sypheos** [comment]
https://www.thethingsnetwork.org/forum/t/the-things-gateway-design/6754

You will several information about the gateway hardware. The modules can be bought from the standard hardware re-seller(Farnel, Microchip,...).

There are constant update on the firmware and don't forget to check the forum.

**Comment by DutchMcGyver** [comment]
@Sypheos I wish it were that simple Sylvain. The LG8271 isn't listed at Farnell, Microchip or Microchip Direct. If it was, I would've ordered one a long time ago. Are there any other sources that you know of that I can try?

**Comment by ketilmo** [comment]
Hi, I'm having the exact same issues as described by @DutchMcGyver in this thread. Assuming this is a hardware issue, is it possible to get replacement LG8271 boards now?

Kind regards,
Ketil

**Comment by DutchMcGyver** [comment]
@ketilmo : Just received this answer directly from Microchip: 

"Please be informed that my colleagues from the business unit in charge for the part number LG8271-I/RM104 told me that this part is End of Life and at the moment there is no replacement part for it."

So essentially, your TTN gateway is now a brick, although in my case it was three months old when the issue occurred. The TTN guys have been absolutely NO help in resolving this issue either. Please think twice before buying anything from TTN again.

**Comment by ketilmo** [comment]
@DutchMcGyver Thanks for letting me know. That's bad news. :(

**Comment by danielkucera** [comment]
@DutchMcGyver I'd buy the broken gateway from you if you still have it...

**Comment by mellbratt** [comment]
@danielkucera – I have one with the same symptoms too, for sale, located in Sweden
